painel/app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
		
	Route::get('/','Auth\AuthController@getLogin');

	Route::post('painel/email',['as' => 'painel.email', 'uses' => 'PainelController@email']);
	Route::post('emails/create',['as' => 'painel.emails.create', 'uses' => 'Api\ApiProjectController@create']);
	Route::get('emails/update/{id}/confirmation',['as' => 'email.confirmation', 'uses' => 'EmailController@emailConfirmation']);
	Route::get('emails/success', ['as' => 'emails.success', 'uses' => 'EmailController@successConfirmation']);

	Route::get('auth/login', 'Auth\AuthController@getLogin');
	Route::post('auth/login', 'Auth\AuthController@postLogin');
	Route::get('auth/logout', 'Auth\AuthController@getLogout');
	Route::get('auth/register', 'Auth\AuthController@getRegister');
	Route::post('auth/register', 'Auth\AuthController@postRegister');

	Route::group(['prefix'=>'admin', 'middleware'=>'verify', 'as'=>'admin.'],function(){
		
		Route::get('home',['as' => 'painel.index', 'uses' => 'PainelController@index']);
		Route::get('painel/register',['as' => 'painel.user', 'uses' => 'PainelController@createUser']);
		Route::post('painel/save',['as' => 'painel.create.user', 'uses' => 'PainelController@saveUser']);
		Route::post('painel/update',['as' => 'painel.create.update', 'uses' => 'PainelController@updateUser']);
		Route::get('painel/edit/{id}',['as' => 'painel.edit.user', 'uses' => 'PainelController@editUser']);
		Route::get('painel/list',['as' => 'painel.userlist', 'uses' => 'PainelController@listUser']);
		Route::get('painel/index',['as' => 'painel.userIndex', 'uses' => 'PainelController@indexList']);

		Route::get('project/register',['as' => 'painel.project', 'uses' => 'ProjectController@createProject']);
		Route::post('project/save',['as' => 'painel.create.project', 'uses' => 'ProjectController@saveProject']);
		Route::get('project/projects',['as' => 'painel.projectView', 'uses' => 'ProjectController@project']);
		Route::get('project/list',['as' => 'painel.projectlist', 'uses' => 'ProjectController@listProject']);
		Route::get('project/edit',['as' => 'painel.projectedit', 'uses' => 'ProjectController@editProject']);
		Route::get('project/edit/{id}',['as' => 'painel.edit', 'uses' => 'ProjectController@edit']);
		Route::get('project/destroy/{id}',['as' => 'painel.destroy', 'uses' => 'ProjectController@destroyProject']);
		Route::post('project/update',['as' => 'painel.update', 'uses' => 'ProjectController@updateProject']);

		Route::get('image/edit/{id}',['as' => 'painel.image', 'uses' => 'ImageController@editImage']);
		// Route::post('image/update/{id}',['as' => 'painel.image.update', 'uses' => 'ImageController@updateImage']);
		Route::post('image/update',['as' => 'painel.image.update', 'uses' => 'ImageController@updateImage']);
		Route::get('image/delete/{id}',['as' => 'painel.image.delete', 'uses' => 'ImageController@deleteImage']);
		Route::post('image/destroy/{id}',['as' => 'painel.image.destroy', 'uses' => 'ImageController@destroyImage']);
		Route::get('image/add/{id}',['as' => 'painel.image.add', 'uses' => 'ImageController@addImage']);
		Route::post('image/save',['as' => 'painel.image.save', 'uses' => 'ImageController@saveImage']);
		Route::post('image/updateOrder',['as' => 'painel.image.updateOrder', 'uses' => 'ImageController@updateOrder']);
		// Route::post('image/save/{id}',['as' => 'painel.image.save', 'uses' => 'ImageController@saveImage']);

		Route::get('image/multiple/{id}',['as' => 'multiple.order', 'uses' => 'ImageController@indexMultiple']);
		Route::post('image/multiple/{id}',['as' => 'image.update.multiple', 'uses' => 'ImageController@updateMultiple']);
		Route::get('image/single/{id}',['as' => 'single.order', 'uses' => 'ImageController@indexSingle']);
		Route::post('image/single/{id}',['as' => 'image.update.single', 'uses' => 'ImageController@updateSingle']);
		
		Route::get('news/create',['as' => 'painel.news.create', 'uses' => 'NewsController@create']);
		Route::get('news/list',['as' => 'painel.news.list', 'uses' => 'NewsController@show']);
		Route::get('news/edit/{id}',['as' => 'painel.news.edit', 'uses' => 'NewsController@edit']);
		Route::post('news/update/{id}',['as' => 'painel.news.update', 'uses' => 'NewsController@update']);

		Route::post('news/send',['as' => 'painel.email.send', 'uses' => 'EmailController@sendEmail']);
		Route::post('news/update/{id}',['as' => 'painel.email.update', 'uses' => 'EmailController@updateSendEmail']);

		Route::get('emails/list',['as' => 'painel.emails.list', 'uses' => 'EmailController@show']);

		Route::get('promotions/list',['as' => 'painel.promotions.list', 'uses' => 'PromotionsController@index']);
		Route::get('promotions/store',['as' => 'painel.promotions.store', 'uses' => 'PromotionsController@store']);
		Route::get('promotions/show',['as' => 'painel.promotions.show', 'uses' => 'PromotionsController@show']);
		Route::get('promotions/edit/{id}',['as' => 'painel.promotions.edit', 'uses' => 'PromotionsController@edit']);
		Route::get('promotions/edit',['as' => 'painel.promotions.image', 'uses' => 'PromotionsController@image']);
		Route::get('promotions/delete/{id}',['as' => 'painel.promotions.delete', 'uses' => 'PromotionsController@delete']);
		Route::post('promotions/create',['as' => 'painel.promotions.create', 'uses' => 'PromotionsController@create']);
		Route::post('promotions/update',['as' => 'painel.promotions.update', 'uses' => 'PromotionsController@update']);
		Route::post('promotions/addNewImage',['as' => 'painel.promotions.addNewImage', 'uses' => 'PromotionsController@addNewImage']);
		Route::post('promotions/updateImage',['as' => 'painel.promotions.updateImage', 'uses' => 'PromotionsController@updateImage']);

		Route::get('bi/projects',['as' => 'painel.projects.count', 'uses' => 'BIController@projectsCount']);
	});
	// Route::get('email/send/multiple',['as' => 'email.send', 'uses' => 'EmailController@sendEmail']);
	
	Route::get('api/project/list',['as' => 'api.project.list', 'uses' => 'Api\ApiProjectController@ApiListProject']);
Route::post('promotions/addNewImage',['as' => 'painel.promotions.addNewImage', 'uses' => 'PromotionsController@addNewImage']);
Route::post('promotions/updateImage',['as' => 'painel.promotions.updateImage', 'uses' => 'PromotionsController@updateImage']);

painel/app/Models/News.php
<?php

namespace Painel\Models;

use Illuminate\Database\Eloquent\Model;
use Prettus\Repository\Contracts\Transformable;
use Prettus\Repository\Traits\TransformableTrait;

class News extends Model implements Transformable
{
    use TransformableTrait;

    protected $fillable = ['title', 'subject', 'description'];

}

painel/app/Http/Controllers/NewsController.php
<?php

namespace Painel\Http\Controllers;

use Illuminate\Http\Request;
use Painel\Http\Controllers\Controller;
use Painel\Http\Requests;
use Painel\Repositories\NewsRepository;

class NewsController extends Controller
{
    private $newsRepository;

    public function __construct(NewsRepository $newsRepository)
    {
        $this->newsRepository = $newsRepository;
    }

    public function create()
    {
        return view('admin.news.create');
    }

    public function save(Request $request)
    {
        dd($request->all());
    }

    public function show()
    {
        $news = $this->newsRepository->paginate(10);

        return view('admin.news.list', compact('news'));
    }

    public function edit($id)
    {
        $news = $this->newsRepository->find($id);

        return view('admin.news.edit', compact('news'));
    }

}

painel/resources/views/admin/news/_form.blade.php
<div class="form-group">
    {!! Form::label('Título', 'Título') !!}
    {!! Form::text('title', null, ['class' => 'form-control', 'required' => 'required']) !!}
</div>

<div class="form-group">
    {!! Form::label('Asssunto', 'Asssunto') !!}
    {!! Form::text('subject', null, ['class' => 'form-control', 'required' => 'required']) !!}
</div>

<div class="form-group">
    {!! Form::label('Descrição', 'Descrição') !!}
    {!! Form::textarea('description', null, ['class' => 'form-control', 'required' => 'required']) !!}
</div>

painel/resources/views/admin/news/create.blade.php
@extends('app')

@section('content')

{!! Html::style('css/style.css') !!}
{!! Html::style('css/altered.css') !!}

<div class="container-fluid align-div-principal">
	<div class="row">
		<div class="col-md-8 col-md-offset-2 align-div-button">
			<div class="panel panel-default">
				<div class="panel-heading"><h4>Crie News e envie para sua lista de E-mails</h4></div>
				<div class="panel-body">
					@if (count($errors) > 0)
						<div class="alert alert-danger">
							<strong>Whoops!</strong> There were some problems with your input.<br><br>
							<ul>
								@foreach ($errors->all() as $error)
									<li>{{ $error }}</li>
								@endforeach
							</ul>
						</div>
					@endif
					{!! Form::open(['route'=>'admin.painel.email.send', 'class'=>'form', 'files'=>true])!!}
					
					<div class="alert alert-warning alert-del-img">
					<strong>Informações Importantes.</strong><br>
						Ao enviar você irá registrar a publicação e logo após será enviado para todos os e-mails ativos na sua lista. <br>
					</div>

						{!! csrf_field() !!}

						@include('admin.news._form')

						<div class="form-group">
							<span class="btn btn-default btn-file">
								{!! Form::file('images[]', array('class'=>'custom-file-input')) !!}
								<span class="glyphicon glyphicon-folder-open"></span> Selecione uma imagem
							</span>
						</div>

						<div class="form-group">
						 	{!! Form::submit('Enviar', ['class'=>'btn btn-primary'])!!}
						</div>

					{!! Form::close()!!}
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

painel/resources/views/admin/news/edit.blade.php
@extends('app')

@section('content')

{!! Html::style('css/style.css') !!}
{!! Html::style('css/altered.css') !!}

<div class="container-fluid align-div-principal">
	<div class="row">
		<div class="col-md-8 col-md-offset-2 align-div-button">
			<div class="panel panel-default">
				<div class="panel-heading"><h4>Editar Publicação: {{$news->title}}</h4></div>
				<div class="panel-body">
					
					@include('errors._check')

					<div class="alert alert-warning alert-del-img">
					<strong>Informações Importantes.</strong><br>
						Você pode alterar a publicação e reenviar ou você pode apenas reenviar sem realizar alterações.
					</div>

					{!! Form::model($news, ['route'=>['admin.painel.email.update', $news->id], 'files'=>true])!!}
					
					{!! csrf_field() !!}

					@include('admin.news._form')

					<div class="form-group">
						<span class="btn btn-default btn-file">
							{!! Form::file('images[]', array('class'=>'custom-file-input')) !!}
							<span class="glyphicon glyphicon-folder-open"></span> Selecione uma imagem
						</span>
					</div>

					<div class="form-group">
					{!! Form::submit('Salvar e Enviar', ['class'=>'btn btn-primary'])!!}
					</div>

					{!! Form::close()!!}
					
				</div>
			</div>
		</div>
	</div>
	@endsection

painel/resources/views/admin/news/list.blade.php
@extends('app')

@section('content')

{!! Html::style('css/style.css') !!}
{!! Html::style('css/altered.css') !!}

<div class="container-fluid align-div-principal">
	<div class="row">
		<div class="col-md-8 col-md-offset-2 align-div-button">
			<div class="panel panel-default">
				<div class="panel-heading"><h4>Lista de publicações</h4></div>
				<div class="panel-body">
					@if (count($errors) > 0)
						<div class="alert alert-danger">
							<strong>Whoops!</strong> There were some problems with your input.<br><br>
							<ul>
								@foreach ($errors->all() as $error)
									<li>{{ $error }}</li>
								@endforeach
							</ul>
						</div>
					@endif
					<table class="table" style="text-align: center;">
						<thead>
							<tr>
								<th style="text-align: center;">ID</th>
								<th style="text-align: center;">Título</th>
								<th style="text-align: center;">Assunto</th>
								<th style="text-align: center;">Editar e Enviar</th>
							</tr>
							<tbody>
								@foreach($news as $new)
								<tr>
									<td>{{$new->id}}</td>
									<td>{{$new->title}}</td>
									<td>{{$new->subject}}</td>
									<td>
										<a href="{{route('admin.painel.news.edit',['id'=>$new->id])}}" class="btn btn-success btn-sm">
											<span class="glyphicon glyphicon-pencil"></span>
											
											<span class="glyphicon glyphicon-send"></span>
										</a>
									</td>
								</tr>
								@endforeach
							</tbody>
						</thead>
					</table>
					{!! $news->render() !!}
				</div>
			</div>
		</div>
	</div>
</div>
@endsection