painel/app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
		
	Route::get('/','Auth\AuthController@getLogin');

	Route::post('painel/email',['as' => 'painel.email', 'uses' => 'PainelController@email']);
	Route::post('emails/create',['as' => 'painel.emails.create', 'uses' => 'Api\ApiProjectController@create']);
	Route::get('emails/update/{id}/confirmation',['as' => 'email.confirmation', 'uses' => 'EmailController@emailConfirmation']);
	Route::get('emails/success', ['as' => 'emails.success', 'uses' => 'EmailController@successConfirmation']);

	Route::get('auth/login', 'Auth\AuthController@getLogin');
	Route::post('auth/login', 'Auth\AuthController@postLogin');
	Route::get('auth/logout', 'Auth\AuthController@getLogout');
	Route::get('auth/register', 'Auth\AuthController@getRegister');
	Route::post('auth/register', 'Auth\AuthController@postRegister');

	Route::group(['prefix'=>'admin', 'middleware'=>'verify', 'as'=>'admin.'],function(){
		
		Route::get('home',['as' => 'painel.index', 'uses' => 'PainelController@index']);
		Route::get('painel/register',['as' => 'painel.user', 'uses' => 'PainelController@createUser']);
		Route::post('painel/save',['as' => 'painel.create.user', 'uses' => 'PainelController@saveUser']);
		Route::post('painel/update',['as' => 'painel.create.update', 'uses' => 'PainelController@updateUser']);
		Route::get('painel/edit/{id}',['as' => 'painel.edit.user', 'uses' => 'PainelController@editUser']);
		Route::get('painel/list',['as' => 'painel.userlist', 'uses' => 'PainelController@listUser']);
		Route::get('painel/index',['as' => 'painel.userIndex', 'uses' => 'PainelController@indexList']);

		Route::get('project/register',['as' => 'painel.project', 'uses' => 'ProjectController@createProject']);
		Route::post('project/save',['as' => 'painel.create.project', 'uses' => 'ProjectController@saveProject']);
		Route::get('project/projects',['as' => 'painel.projectView', 'uses' => 'ProjectController@project']);
		Route::get('project/list',['as' => 'painel.projectlist', 'uses' => 'ProjectController@listProject']);
		Route::get('project/edit',['as' => 'painel.projectedit', 'uses' => 'ProjectController@editProject']);
		Route::get('project/edit/{id}',['as' => 'painel.edit', 'uses' => 'ProjectController@edit']);
		Route::get('project/destroy/{id}',['as' => 'painel.destroy', 'uses' => 'ProjectController@destroyProject']);
		Route::post('project/update',['as' => 'painel.update', 'uses' => 'ProjectController@updateProject']);

		Route::get('image/edit/{id}',['as' => 'painel.image', 'uses' => 'ImageController@editImage']);
		// Route::post('image/update/{id}',['as' => 'painel.image.update', 'uses' => 'ImageController@updateImage']);
		Route::post('image/update',['as' => 'painel.image.update', 'uses' => 'ImageController@updateImage']);
		Route::get('image/delete/{id}',['as' => 'painel.image.delete', 'uses' => 'ImageController@deleteImage']);
		Route::post('image/destroy/{id}',['as' => 'painel.image.destroy', 'uses' => 'ImageController@destroyImage']);
		Route::get('image/add/{id}',['as' => 'painel.image.add', 'uses' => 'ImageController@addImage']);
		Route::post('image/save',['as' => 'painel.image.save', 'uses' => 'ImageController@saveImage']);
		Route::post('image/updateOrder',['as' => 'painel.image.updateOrder', 'uses' => 'ImageController@updateOrder']);
		// Route::post('image/save/{id}',['as' => 'painel.image.save', 'uses' => 'ImageController@saveImage']);

		Route::get('image/multiple/{id}',['as' => 'multiple.order', 'uses' => 'ImageController@indexMultiple']);
		Route::post('image/multiple/{id}',['as' => 'image.update.multiple', 'uses' => 'ImageController@updateMultiple']);
		Route::get('image/single/{id}',['as' => 'single.order', 'uses' => 'ImageController@indexSingle']);
		Route::post('image/single/{id}',['as' => 'image.update.single', 'uses' => 'ImageController@updateSingle']);
		
		Route::get('news/create',['as' => 'painel.news.create', 'uses' => 'NewsController@create']);
		Route::get('news/list',['as' => 'painel.news.list', 'uses' => 'NewsController@show']);
		Route::get('news/edit/{id}',['as' => 'painel.news.edit', 'uses' => 'NewsController@edit']);
		Route::post('news/update/{id}',['as' => 'painel.news.update', 'uses' => 'NewsController@update']);

		Route::post('news/send',['as' => 'painel.email.send', 'uses' => 'EmailController@sendEmail']);
		Route::post('news/update/{id}',['as' => 'painel.email.update', 'uses' => 'EmailController@updateSendEmail']);

		Route::get('emails/list',['as' => 'painel.emails.list', 'uses' => 'EmailController@show']);

		Route::get('promotions/list',['as' => 'painel.promotions.list', 'uses' => 'PromotionsController@index']);
		Route::get('promotions/store',['as' => 'painel.promotions.store', 'uses' => 'PromotionsController@store']);
		Route::get('promotions/show',['as' => 'painel.promotions.show', 'uses' => 'PromotionsController@show']);
		Route::get('promotions/edit/{id}',['as' => 'painel.promotions.edit', 'uses' => 'PromotionsController@edit']);
		Route::get('promotions/edit',['as' => 'painel.promotions.image', 'uses' => 'PromotionsController@image']);
		Route::get('promotions/delete/{id}',['as' => 'painel.promotions.delete', 'uses' => 'PromotionsController@delete']);
		Route::post('promotions/create',['as' => 'painel.promotions.create', 'uses' => 'PromotionsController@create']);
		Route::post('promotions/update',['as' => 'painel.promotions.update', 'uses' => 'PromotionsController@update']);
		Route::post('promotions/addNewImage',['as' => 'painel.promotions.addNewImage', 'uses' => 'PromotionsController@addNewImage']);
		Route::post('promotions/updateImage',['as' => 'painel.promotions.updateImage', 'uses' => 'PromotionsController@updateImage']);

		Route::get('bi/projects',['as' => 'painel.projects.count', 'uses' => 'BIController@projectsCount']);
	});
	// Route::get('email/send/multiple',['as' => 'email.send', 'uses' => 'EmailController@sendEmail']);
	
	Route::get('api/project/list',['as' => 'api.project.list', 'uses' => 'Api\ApiProjectController@ApiListProject']);
Route::post('promotions/addNewImage',['as' => 'painel.promotions.addNewImage', 'uses' => 'PromotionsController@addNewImage']);
Route::post('promotions/updateImage',['as' => 'painel.promotions.updateImage', 'uses' => 'PromotionsController@updateImage']);

painel/resources/views/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Painel - Admin</title>
	 <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.2.6/angular.min.js"></script>
	<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet">

	<!-- Fonts -->
	<script src="http://code.jquery.com/jquery-latest.min.js" type="text/javascript"></script>
	<link href='//fonts.googleapis.com/css?family=Roboto:400,300' rel='stylesheet' type='text/css'>
	
	{!! Html::script('js/angular/lib/snackbar/snack.js') !!}
	{!! Html::style('js/angular/lib/snackbar/snack.css') !!}
	{!! Html::style('css/style.css') !!}
	{!! Html::style('css/altered.css') !!}
	
	{!! Html::script('js/menu/menu.js') !!}

	<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
		<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
		<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<![endif]-->
</head>
<body>
	<nav class="navbar navbar-default">
		<div class="container-fluid">
			<div class="navbar-header">
				<a class="navbar-brand" href="http://marceloprogrammer.com">Marcelo Programmer</a>
			</div>
		</div>
	</nav>
	@if(Auth::user())
	<div class="menu-vertical" id='cssmenu'>
		<ul id="nav" class="menu-vertical-nav"> 
			<li class='active'><a href='#'><span>Menu</span></a></li>
			<li class='has-sub'><a href='#'><span>Usuário</span></a>
				<ul>
					<li><a href="{{route('admin.painel.user') }}"><span>Criar</span></a></li>
					<li class='last'><a href="{{route('admin.painel.userlist') }}"><span>Listar</span></a></li>
				</ul>
			</li>
			<li class='has-sub'><a href='#'><span>Projetos</span></a>
				<ul>
					<li><a href="{{route('admin.painel.project') }}"><span>Criar</span></a></li>
					<li class='last'><a href="{{route('admin.painel.projectView') }}"><span>Exibir</span></a></li>
				</ul>
			</li>
			<li class='has-sub'><a href='#'><span>Promoções</span></a>
				<ul>
					<li><a href="{{route('admin.painel.promotions.store') }}"><span>Criar</span></a></li>
					<li class='last'><a href="{{route('admin.painel.promotions.list') }}"><span>Exibir</span></a></li>
					<li class='last'><a href="{{route('admin.painel.promotions.list') }}"><span>Visualizar</span></a></li>
				</ul>
			</li>
			<li class='has-sub'><a href='#'><span>Publicações</span></a>
				<ul>
					<li><a href="{{route('admin.painel.news.create') }}"><span>Enviar</span></a></li>
					<li class='last'><a href="{{route('admin.painel.news.list') }}"><span>Exibir</span></a></li>
				</ul>
			</li>
			<li class='has-sub'><a href='#'><span>E-mails</span></a>
				<ul>
					<li class='last'><a href="{{route('admin.painel.emails.list') }}"><span>Exibir</span></a></li>
				</ul>
			</li>
			<li class='has-sub'><a href='#'><span>Imagem</span></a>
				<ul>
					<li class='last'><a href="{{route('admin.painel.projectedit') }}"><span>Projeto</span></a></li>
					<li class='last'><a href="{{route('admin.painel.promotions.image') }}"><span>Promoção</span></a></li>
				</ul>
			</li>
			<li class='has-sub'><a href='#'><span>{{ auth()->user()->name }} </span></a>
				<ul>
					<li class='last'><a href="{{ url('/auth/logout') }}"><span>Sair</span></a></li>
				</ul>
			</li>
		</ul>
	</div>
	@endif
	@yield('content')

	<!-- Scripts -->
	<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
	<script src="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.5/js/bootstrap.min.js"></script>

	@yield('post-script')

	<footer class="footer">
		<div class="footer-text">
			<div>
				Painel - V 1.0
			</div>
			<div>
				© Marcelo Nascimento - Todos os direitos reservados.
			</div>
		</div>
	</footer>
</body>
</html>

painel/resources/views/app_old.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Painel - Admin</title>
	 <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.2.6/angular.min.js"></script>
	<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet">

	<!-- Fonts -->
	<script src="http://code.jquery.com/jquery-latest.min.js" type="text/javascript"></script>
	<link href='//fonts.googleapis.com/css?family=Roboto:400,300' rel='stylesheet' type='text/css'>
	
	{!! Html::script('js/angular/lib/snackbar/snack.js') !!}
	{!! Html::style('js/angular/lib/snackbar/snack.css') !!}
	{!! Html::style('css/style.css') !!}
	
	{!! Html::script('js/menu/menu.js') !!}

	<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
		<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
		<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<![endif]-->
</head>
<body>
	<nav class="navbar navbar-default">
		<div class="container-fluid">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
					<span class="sr-only">Toggle Navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="http://marceloprogrammer.com">Marcelo Programmer</a>
			</div>

			<div class="collapse navbar-collapse" id="navbar">
				<ul class="nav navbar-nav">
				@if(Auth::user())
					<ul class="nav navbar-nav">
						<li><a href="{{route('admin.painel.index')}}">Home</a></li>
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Usuário<span class="caret"></span></a>
							<ul class="dropdown-menu" role="menu">
								<li><a href="{{route('admin.painel.user') }}">Criar</a></li>
								<li><a href="{{route('admin.painel.userlist') }}">Exibir</a></li>
							</ul>
						</li>
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Projetos<span class="caret"></span></a>
							<ul class="dropdown-menu" role="menu">
								<li><a href="{{route('admin.painel.project') }}">Criar</a></li>
								<li><a href="{{route('admin.painel.projectView') }}">Exibir</a></li>
							</ul>
						</li>
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Image<span class="caret"></span></a>
							<ul class="dropdown-menu" role="menu">
								<li><a href="{{route('admin.painel.projectedit') }}">Gerenciar</a></li>
							</ul>
						</li>
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Publicações<span class="caret"></span></a>
							<ul class="dropdown-menu" role="menu">
								<li><a href="{{route('admin.painel.news.create') }}">Enviar</a></li>
								<li><a href="{{route('admin.painel.news.list') }}">Exibir</a></li>
							</ul>
						</li>
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">E-mails<span class="caret"></span></a>
							<ul class="dropdown-menu" role="menu">
								
								<li><a href="{{route('admin.painel.emails.list') }}">Exibir</a></li>
							</ul>
						</li>
					</ul>
				@endif
				</ul>

				<ul class="nav navbar-nav navbar-right">
					@if(!auth()->guest())
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">{{ auth()->user()->name }} <span class="caret"></span></a>
							<ul class="dropdown-menu" role="menu">
								<li><a href="{{ url('/auth/logout') }}">Sair</a></li>
							</ul>
						</li>
					@endif
				</ul>
			</div>
		</div>
	</nav>
	@if(Auth::user())
	<div class="menu-vertical" id='cssmenu'>
		<ul id="nav" class="menu-vertical-nav"> 
			<li class='active'><a href='#'><span>Menu</span></a></li>
			<li class='has-sub'><a href='#'><span>Usuário</span></a>
				<ul>
					<li><a href="{{route('admin.painel.user') }}"><span>Criar</span></a></li>
					<li class='last'><a href="{{route('admin.painel.userlist') }}"><span>Listar</span></a></li>
				</ul>
			</li>
			<li class='has-sub'><a href='#'><span>Projetos</span></a>
				<ul>
					<li><a href="{{route('admin.painel.project') }}"><span>Criar</span></a></li>
					<li class='last'><a href="{{route('admin.painel.projectView') }}"><span>Exibir</span></a></li>
				</ul>
			</li>
			<li class='has-sub'><a href='#'><span>Image</span></a>
				<ul>
					<li class='last'><a href="{{route('admin.painel.projectedit') }}"><span>Gerenciar</span></a></li>
				</ul>
			</li>
			<li class='has-sub'><a href='#'><span>Publicações</span></a>
				<ul>
					<li><a href="{{route('admin.painel.news.create') }}"><span>Enviar</span></a></li>
					<li class='last'><a href="{{route('admin.painel.news.list') }}"><span>Exibir</span></a></li>
				</ul>
			</li>
			<li class='has-sub'><a href='#'><span>E-mails</span></a>
				<ul>
					<li class='last'><a href="{{route('admin.painel.emails.list') }}"><span>Exibir</span></a></li>
				</ul>
			</li>
			<li class='has-sub'><a href='#'><span>{{ auth()->user()->name }} </span></a>
				<ul>
					<li class='last'><a href="{{ url('/auth/logout') }}"><span>Sair</span></a></li>
				</ul>
			</li>
		</ul>
	</div>
	@endif
	@yield('content')

	<!-- Scripts -->
	<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
	<script src="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.5/js/bootstrap.min.js"></script>

	@yield('post-script')

	<footer class="footer">
		<div class="footer-text">
			<div>
				Painel - V 1.0
			</div>
			<div>
				© Marcelo Nascimento - Todos os direitos reservados.
			</div>
		</div>
	</footer>
</body>
</html>

painel/resources/views/home.blade.php
@extends('app')

@section('content')
<div class="container">
	<div class="row">
		<div class="col-md-10 col-md-offset-1">
			<div class="panel panel-default">
				<!-- <div class="panel-heading">Home</div>

				<div class="panel-body">
					You are logged in!
				</div> -->
			</div>
		</div>
	</div>
</div>
@endsection